version: '3'
services:
  bff:
    image: ghcr.io/mochizuki875/bookreview-bff:v1.0
    ports:
      - "8080:8080"
    environment:
      - buildEnv=dev
      - SERVER_PORT=8080
      - BOOK_API_URL=http://book-api:8080/api/book
      - REVIEW_API_URL=http://review-api:8080/api/review
  book-api:
    image: ghcr.io/mochizuki875/book-api:v1.0
    ports:
      - "8081:8080"
    environment:
      - buildEnv=dev
      - SERVER_PORT=8080
      - REVIEW_API_URL=http://review-api:8080/api/review
  review-api:
    image: ghcr.io/mochizuki875/review-api:v1.0
    ports:
      - "8082:8080"
    environment:
      - buildEnv=dev
      - SERVER_PORT=8080
      - BOOK_API_URL=http://book-api:8080/api/book